FROM openjdk:8-jdk-stretch

# OS setup
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update
RUN apt-get install -y gradle jq git-core curl build-essential openssl libssl-dev nodejs rsync

RUN npm i -g run-func

# Android tools
WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q \
    && unzip -q sdk-tools-linux-4333796.zip \
    && rm sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools" "build-tools;28.0.3"
ENV PATH="${PATH}:/sdk/platform-tools"

ENV ANDROID_HOME="/sdk/"
ENV GRADLE_OPTS="-Dorg.gradle.daemon=false"

WORKDIR /app

# npm auth
RUN rm -f ~/.npmrc
ARG REG_BASIC_CREDENTIAL
ARG REG_NPM_EMAIL
RUN echo "_auth=$REG_BASIC_CREDENTIAL" >> ~/.npmrc
RUN echo "email=$REG_NPM_EMAIL" >> ~/.npmrc
RUN echo "always-auth=true" >> ~/.npmrc
