FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/js:base-ci

# Copy in all the files needed to build
COPY .git .git

# Do a full build by running the container
CMD run-func scripts/react-native-helper.js build "/app/test/react-native/features/fixtures" "/app/features/fixtures"
