FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/js:rn-android-base

# Prepare Gradle folders to avoid downloading Gradle again when the Docker cache is invalidated by changing source
# First we copy the skeleton files gathered in advance of the Docker build using react-native-helper.gather().
COPY lerna.json .
COPY scripts/common.js scripts/react-native-helper.js scripts/
COPY docker-temp/fixtures /app/features/fixtures/
# Just runs ./gradlew build currently...
RUN run-func scripts/react-native-helper.js prepare /app/features/fixtures

# Now copy in all the files needed to build
COPY .git .git

# Do a full build by running the container
CMD run-func scripts/react-native-helper.js build "/app/test/react-native/features/fixtures" "/app/features/fixtures"
